### ISSUE TITLE
Want to add CODE_OF_CONDUCT.md and also Contributing.md

### ISSUE THREAD

**Issue by sb-decoder** [CPAD-Gazipur/Poi-Poi-ToDo#2]
Do you want this changes?

**Comment by alamin-karno** [comment]
> Do you want this changes?

OK

**Comment by alamin-karno** [comment]
You have close the PR before merged.

**Comment by sb-decoder** [comment]
> You have close the PR before merged.

Sorry , In that PR I did a mistake, so I did that

**Comment by sb-decoder** [comment]
> You have close the PR before merged.

I have made another PR , @alamin-karno please check

**Comment by alamin-karno** [comment]
Merged
